# Generated by Django 4.1 on 2022-08-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="poll", name="creator",),
    ]
