# Generated by Django 4.1 on 2022-08-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0002_remove_poll_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date published"
            ),
        ),
    ]
