# Generated by Django 4.1 on 2022-08-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0005_poll_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="poll_number", name="profile",),
    ]
